apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mixed
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: app-of-mixed-resources
      repoURL: https://github.com/massimob76/argocd-playground.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true