apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: slow-start-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: slow-start-1
            namespace: slow-start-1
            wave: 2
          - name: slow-start-2
            namespace: slow-start-2
            wave: 1
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: wave
              operator: In
              values:
                - "1"
        - matchExpressions:
            - key: wave
              operator: In
              values:
                - "2"
  template:
    metadata:
      name: '{{.name}}'
      namespace: argocd
      labels:
        wave: '{{.wave}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        namespace: '{{.namespace}}'
        server: https://kubernetes.default.svc
      project: default
      source:
        path: deployment
        repoURL: https://github.com/massimob76/argocd-playground.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
