apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: guestbook-1
            namespace: guestbook-a
            wave: 1
          - name: guestbook-2
            namespace: guestbook-b
            wave: 2
          - name: guestbook-3
            namespace: guestbook-c
            wave: 3
  template:
    metadata:
      name: '{{.name}}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{.wave}}'
    spec:
      destination:
        namespace: '{{.namespace}}'
        server: https://kubernetes.default.svc
      project: default
      source:
        path: guestbook
        repoURL: https://github.com/argoproj/argocd-example-apps
        targetRevision: master
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true