apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: slow-start-appset-part-2
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '3'
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: slow-start-3
            namespace: slow-start-3
            wave: 2
          - name: slow-start-4
            namespace: slow-start-4
            wave: 1
  template:
    metadata:
      name: '{{.name}}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{.wave}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        namespace: '{{.namespace}}'
        server: https://kubernetes.default.svc
      project: default
      source:
        path: deployment
        repoURL: https://github.com/massimob76/argocd-playground.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
