apiVersion: batch/v1
kind: Job
metadata:
  name: wait-box
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    metadata:
      labels:
        app: wait-box
    spec:
      containers:
        - name: busybox
          image: registry.k8s.io/busybox
          args:
            - /bin/sh
            - -c
            - 'sleep 15'
      restartPolicy: Never
  backoffLimit: 1
