apiVersion: batch/v1
kind: Job
metadata:
  name: wait-box
spec:
  template:
    metadata:
      labels:
        app: wait-box
    spec:
      containers:
        - name: busybox
          image: registry.k8s.io/busybox
          args:
            - /bin/sh
            - -c
            - 'trap : TERM INT; echo "waiting..."; sleep 15; touch /tmp/healthy; echo "started"; sleep 30 & wait'
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/healthy
            initialDelaySeconds: 10
            periodSeconds: 5
      restartPolicy: Never
  backoffLimit: 4
