apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-service
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: nginx-service
            namespace: nginx-service
  template:
    metadata:
      name: '{{.name}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        namespace: '{{.namespace}}'
        server: https://kubernetes.default.svc
      project: default
      source:
        path: deployment-nginx
        repoURL: https://github.com/massimob76/argocd-playground.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
